name: "data_transformation_common_pattern_dbt"
version: "1.0.0"
config-version: 2

profile: "data_transformation_common_pattern_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_transformation_common_pattern_dbt:
    +materialized: view
    +on_schema_change: "sync_all_columns"
    +required_fields: []

    staging:
      +materialized: view
      +tags: ["staging"]
      +required_fields: []

    raw:
      +materialized: view
      +tags: ["raw"]
      +required_fields: []

    intermediate:
      +materialized: view
      +tags: ["intermediate"]
      +required_fields: []

    marts:
      +materialized: table
      +tags: ["marts"]
      +required_fields: []

seeds:
  data_transformation_common_pattern_dbt:
    +quote_columns: false

snapshots:
  data_transformation_common_pattern_dbt:
    +target_schema: snapshots
    +strategy: timestamp
    +unique_key: id
    +updated_at: updated_at
