server {
    listen 8080;
    server_name _;

    location / {
        # Changed from 127.0.0.1 to localhost
        #proxy_pass http://localhost:4213;
        proxy_pass http://[::1]:4213;
        # Critical headers
        proxy_set_header Host localhost:4213;
        proxy_set_header Origin http://localhost:4213;
        proxy_set_header Referer http://localhost:4213/;

        # Optional but helpful
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header X-Real-IP 127.0.0.1;

        proxy_http_version 1.1;
    }
}
